import { createHash } from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { cp, mkdir, readFile, writeFile, mkdtemp } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { aws, capture, verify as recoveryVerify } from './recovery-tool.mjs';
import { verify as releaseVerify } from './release-bundle.mjs';
const execute = promisify(execFile);
const digest = b => createHash('sha256').update(b).digest('hex');
const json = v => `${JSON.stringify(v,null,2)}\n`;
export const target = {bucket:'uaroute.com',distribution:'E3L95CZFIU6533',account:'863809951348'};
export const recoveryBucket='uaroute-recovery-863809951348-eu-central-1';
const functionName='uaroute-seo-viewer-request-v1';
export function validatePrefix(prefix){if(!/^releases\/[0-9]+-[0-9]+$/.test(prefix))throw Error('invalid recovery prefix');return prefix;}
async function cli(args){await execute('aws',args,{maxBuffer:20*1024*1024});}
async function identity(){if((await aws(['sts','get-caller-identity'])).Account!==target.account)throw Error('AWS account mismatch');}
async function assertConfig(bundle){const m=JSON.parse(await readFile(path.join(bundle,'recovery-manifest.json'),'utf8'));const saved=JSON.parse(await readFile(path.join(bundle,m.config.path),'utf8'));const now=await aws(['cloudfront','get-distribution-config','--id',target.distribution]);if(json(saved)!==json(now))throw Error('production distribution drift');return m;}
async function exclusiveAssociations(){const d=await aws(['cloudfront','list-distributions']);const matches=(d.DistributionList?.Items??[]).filter(x=>[x.DefaultCacheBehavior,...(x.CacheBehaviors?.Items??[])].some(b=>(b.FunctionAssociations?.Items??[]).some(a=>a.FunctionARN.endsWith(`/${functionName}`))));if(matches.length!==1||matches[0].Id!==target.distribution)throw Error('unexpected shared edge function association');}
export async function putFile(bucket,key,file,metadata){const input={Bucket:bucket,Key:key,...metadata};const filename=path.join(await mkdtemp(path.join(os.tmpdir(),'uaroute-put-')),'input.json');await writeFile(filename,json(input));await aws(['s3api','put-object','--cli-input-json',`file://${filename}`,'--body',file]);}
async function edgePublish(code,config){await exclusiveAssociations();const live=await aws(['cloudfront','describe-function','--name',functionName,'--stage','LIVE']);const current=path.join(await mkdtemp(path.join(os.tmpdir(),'uaroute-edge-')),'live.js');await aws(['cloudfront','get-function','--name',functionName,'--stage','LIVE',current]);if(digest(await readFile(current))===digest(await readFile(code))&&json(live.FunctionSummary.FunctionConfig)===json(config))return {changed:false};const dev=await aws(['cloudfront','describe-function','--name',functionName,'--stage','DEVELOPMENT']);const configFile=path.join(path.dirname(current),'config.json');await writeFile(configFile,json(config));const updated=await aws(['cloudfront','update-function','--name',functionName,'--if-match',dev.ETag,'--function-config',`file://${configFile}`,'--function-code',`fileb://${path.resolve(code)}`]);
 const cases=[{uri:'/contacts',querystring:{utm_source:{value:'uaroute'}},response:308,location:'https://uaroute.com/about/?utm_source=uaroute'},{uri:'/referral-contract.json',querystring:{},uriExpected:'/referral-contract.json'},{uri:'/provider/unknown',querystring:{},response:404},{uri:'/missing.js',querystring:{},uriExpected:'/missing.js'}];
 for(let i=0;i<cases.length;i++){const c=cases[i];const event={version:'1.0',context:{eventType:'viewer-request'},viewer:{ip:'192.0.2.1'},request:{method:'GET',uri:c.uri,querystring:c.querystring,headers:{host:{value:'uaroute.com'}},cookies:{}}};const file=path.join(path.dirname(current),`test-${i}.json`);await writeFile(file,json(event));const test=await aws(['cloudfront','test-function','--name',functionName,'--if-match',updated.ETag,'--stage','DEVELOPMENT','--event-object',`fileb://${file}`]);const result=JSON.parse(test.TestResult.FunctionOutput);if(test.TestResult.FunctionErrorMessage||(c.response?Number(result.statusCode)!==c.response||c.location&&result.headers.location.value!==c.location:result.uri!==c.uriExpected))throw Error('edge runtime acceptance failed');}
 await aws(['cloudfront','publish-function','--name',functionName,'--if-match',updated.ETag]);return {changed:true};}
export function objectMetadata(meta){return Object.fromEntries(['ContentType','CacheControl','ContentEncoding','ContentDisposition','ContentLanguage','Expires','Metadata','WebsiteRedirectLocation'].filter(k=>meta[k]!==undefined).map(k=>[k,meta[k]]));}
async function finish(evidence){await cli(['cloudfront','wait','distribution-deployed','--id',target.distribution]);const result=await aws(['cloudfront','create-invalidation','--distribution-id',target.distribution,'--paths','/*']);await writeFile(path.join(evidence,'invalidation-created.json'),json(result));await cli(['cloudfront','wait','invalidation-completed','--distribution-id',target.distribution,'--id',result.Invalidation.Id]);await writeFile(path.join(evidence,'invalidation-completed.json'),json(await aws(['cloudfront','get-invalidation','--distribution-id',target.distribution,'--id',result.Invalidation.Id])));}
export async function verifyPublished(files,bucket=target.bucket){for(const f of files){const meta=await aws(['s3api','head-object','--bucket',bucket,'--key',f.key]);if(meta.ContentLength!==f.size)throw Error(`published size mismatch ${f.key}`);const tmp=path.join(await mkdtemp(path.join(os.tmpdir(),'uaroute-verify-')),'object');await aws(['s3api','get-object','--bucket',bucket,'--key',f.key,tmp]);if(digest(await readFile(tmp))!==f.sha256)throw Error(`published hash mismatch ${f.key}`);if(f.metadata)for(const [k,v] of Object.entries(objectMetadata(f.metadata)))if(json(meta[k])!==json(v))throw Error(`published metadata mismatch ${f.key} ${k}`);}}
async function backup({prefix,evidence}){validatePrefix(prefix);const version=await aws(['s3api','get-bucket-versioning','--bucket',recoveryBucket]);const block=await aws(['s3api','get-public-access-block','--bucket',recoveryBucket]);if(version.Status!=='Enabled'||Object.values(block.PublicAccessBlockConfiguration).some(x=>x!==true))throw Error('private versioned recovery bucket required');const captured=path.join(evidence,'captured');const manifest=await capture({to:captured,...target});await cli(['s3','cp',captured,`s3://${recoveryBucket}/${prefix}/`,'--recursive','--no-progress','--sse','AES256']);const retrieved=path.join(evidence,'retrieved');await cli(['s3','cp',`s3://${recoveryBucket}/${prefix}/`,retrieved,'--recursive','--no-progress']);await recoveryVerify({bundle:retrieved,expectedHash:manifest.bundleSha256,...target});await writeFile(path.join(evidence,'recovery-receipt.json'),json({prefix,bundleSha256:manifest.bundleSha256,bucket:recoveryBucket,objects:manifest.objects.length,retrievedAt:new Date().toISOString(),retrievalVerified:true}));return {bundle:retrieved,manifest};}
export async function deploy(o){await mkdir(o.evidence,{recursive:true});const run=JSON.parse(await readFile(o.run,'utf8'));await releaseVerify({...o,run});await identity();const recovery=await backup(o);await assertConfig(recovery.bundle);await exclusiveAssociations();const saved=JSON.parse(await readFile(path.join(recovery.bundle,recovery.manifest.functions.find(f=>f.arn.endsWith(`/${functionName}`)).description.path),'utf8'));const manifest=JSON.parse(await readFile(path.join(o.bundle,'manifest.json'),'utf8'));const files=[...manifest.files].sort((a,b)=>Number(b.path.startsWith('_next/static/'))-Number(a.path.startsWith('_next/static/')));for(const f of files){const type=f.path.endsWith('.html')?'text/html; charset=utf-8':f.path.endsWith('.txt')?'text/plain; charset=utf-8':f.path.endsWith('.json')?'application/json':f.path.endsWith('.xml')?'application/xml':undefined;const args=['s3','cp',path.join(o.bundle,'out',f.path),`s3://${target.bucket}/${f.path}`,'--no-progress','--cache-control',f.path.startsWith('_next/static/')?'public, max-age=31536000, immutable':'public, max-age=0, must-revalidate'];if(type)args.push('--content-type',type);await cli(args);}
 await edgePublish(path.join(o.bundle,'edge.js'),saved.FunctionSummary.FunctionConfig);await finish(o.evidence);await verifyPublished(files.map(f=>({...f,key:f.path})));const contract=await fetch('https://uaroute.com/referral-contract.json');if(!contract.ok||!(contract.headers.get('content-type')??'').includes('application/json')||digest(Buffer.from(await contract.arrayBuffer()))!==digest(await readFile(path.join(o.bundle,'out','referral-contract.json'))))throw Error('live receiver contract mismatch');await cp(path.join(o.bundle,'out'),'out',{recursive:true});await execute('node',['scripts/seo-http.mjs','https://uaroute.com','--output',path.join(o.evidence,'live-http.json')],{maxBuffer:20*1024*1024});await writeFile(path.join(o.evidence,'success.json'),json({sourceSha:o.sha,runId:o.runId,releaseSha256:o.expectedHash,edgeSha256:o.expectedEdgeHash,recoveryPrefix:o.prefix,recoveryHash:recovery.manifest.bundleSha256,publishedObjects:files.length,verifiedAt:new Date().toISOString()}));}
export async function rollback(o){validatePrefix(o.prefix);await identity();await mkdir(o.evidence,{recursive:true});const current=await backup({prefix:o.currentPrefix,evidence:path.join(o.evidence,'before-rollback')});await cp(path.join(o.evidence,'before-rollback','recovery-receipt.json'),path.join(o.evidence,'recovery-receipt.json'));const bundle=path.join(o.evidence,'retrieved');await cli(['s3','cp',`s3://${recoveryBucket}/${o.prefix}/`,bundle,'--recursive','--no-progress']);const m=await recoveryVerify({bundle,expectedHash:o.expectedHash,...target});await exclusiveAssociations();const captured=JSON.parse(await readFile(path.join(bundle,m.config.path),'utf8'));const now=await aws(['cloudfront','get-distribution-config','--id',target.distribution]);if(json(now.DistributionConfig)!==json(captured.DistributionConfig))throw Error('rollback distribution config changed; reviewed manual recovery required');await assertConfig(current.bundle);for(const obj of [...m.objects].sort((a,b)=>Number(b.key.startsWith('_next/static/'))-Number(a.key.startsWith('_next/static/'))))await putFile(target.bucket,obj.key,path.join(bundle,obj.path),objectMetadata(obj.metadata));for(const f of m.functions){if(!f.arn.endsWith(`/${functionName}`))throw Error('unexpected rollback function');const desc=JSON.parse(await readFile(path.join(bundle,f.description.path),'utf8'));await edgePublish(path.join(bundle,f.code.path),desc.FunctionSummary.FunctionConfig);}await finish(o.evidence);await verifyPublished(m.objects);await writeFile(path.join(o.evidence,'success.json'),json({mode:'rollback',currentRecoveryPrefix:o.currentPrefix,currentRecoveryHash:current.manifest.bundleSha256,prefix:o.prefix,bundleSha256:m.bundleSha256,verifiedObjects:m.objects.length,verifiedAt:new Date().toISOString()}));}
async function main(){const [mode,...args]=process.argv.slice(2);const o={};for(let i=0;i<args.length;i+=2){if(!args[i].startsWith('--')||!args[i+1])throw Error('expected --key value');o[args[i].slice(2)]=args[i+1];}if(mode==='deploy')await deploy(o);else if(mode==='rollback')await rollback(o);else throw Error('use deploy or rollback');}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))main().catch(e=>{console.error(e.message);process.exitCode=1;});
