import { createHash } from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { cp, mkdir, readFile, writeFile, mkdtemp } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { aws, capture, verify as recoveryVerify } from './recovery-tool.mjs';
import { verify as releaseVerify } from './release-bundle.mjs';
const execute = promisify(execFile);
const digest = b => createHash('sha256').update(b).digest('hex');
const json = v => `${JSON.stringify(v,null,2)}\n`;
export const target = {bucket:'uaroute.com',distribution:'E3L95CZFIU6533',account:'863809951348'};
export const recoveryBucket='uaroute-recovery-863809951348-eu-central-1';
const functionName='uaroute-seo-viewer-request-v1';
export const baseEdgeRuntimeCases=[{uri:'/contacts',querystring:{utm_source:{value:'uaroute'}},response:308,location:'https://uaroute.com/about/?utm_source=uaroute'},{uri:'/referral-contract.json',querystring:{},uriExpected:'/referral-contract.json'},{uri:'/provider/unknown',querystring:{},response:404},{uri:'/missing.js',querystring:{},uriExpected:'/missing.js'}];
export const edgeRuntimeCases=[...baseEdgeRuntimeCases,{method:'GET',uri:'/cities/celle/',querystring:{},uriExpected:'/cities/celle/index.html'},{method:'HEAD',uri:'/cities/celle/',querystring:{},uriExpected:'/cities/celle/index.html'},{method:'GET',uri:'/cities/celle/',headers:{rsc:{value:'1'}},querystring:{},uriExpected:'/cities/celle/index.txt'},{method:'GET',uri:'/cities/celle',querystring:{utm_source:{value:'uaroute'}},response:308,location:'https://uaroute.com/cities/celle/?utm_source=uaroute'},{method:'GET',uri:'/cities/stryi/',querystring:{},response:404},{method:'GET',uri:'/routes/celle-stryi/',querystring:{},response:404}];
function edgeEvent(c){return {version:'1.0',context:{eventType:'viewer-request'},viewer:{ip:'192.0.2.1'},request:{method:c.method??'GET',uri:c.uri,querystring:c.querystring??{},headers:{host:{value:'uaroute.com'},...(c.headers??{})},cookies:{}}};}
function expectedFor(c){return c.response?{statusCode:c.response,...(c.location?{location:c.location}:{})}:{uri:c.uriExpected};}
export function inspectEdgeRuntimeCase(testCase,testResult,index=0){
 const expected=expectedFor(testCase);let envelope;let parseError=false;
 try{envelope=typeof testResult?.TestResult?.FunctionOutput==='string'?JSON.parse(testResult.TestResult.FunctionOutput):testResult?.TestResult?.FunctionOutput;}catch{parseError=true;}
 const envelopeKeys=envelope&&typeof envelope==='object'&&!Array.isArray(envelope)?Object.keys(envelope).sort():[];
 const hasResponse=Boolean(envelope&&typeof envelope==='object'&&envelope.response&&typeof envelope.response==='object');
 const hasRequest=Boolean(envelope&&typeof envelope==='object'&&envelope.request&&typeof envelope.request==='object');
 const payloadCandidate=hasResponse?envelope.response:hasRequest?envelope.request:null;
 const headersValid=payloadCandidate?.headers===undefined||Boolean(payloadCandidate.headers&&typeof payloadCandidate.headers==='object'&&!Array.isArray(payloadCandidate.headers));
 const kindValid=hasResponse?typeof payloadCandidate?.statusCode==='number':hasRequest?typeof payloadCandidate?.uri==='string':false;
 const shapeValid=!parseError&&envelope&&typeof envelope==='object'&&!Array.isArray(envelope)&&hasResponse!==hasRequest&&Object.keys(envelope).length===1&&kindValid&&headersValid;
 const payload=hasResponse?envelope.response:hasRequest?envelope.request:null;
 const headers=payload?.headers??{};const rawLocation=headers?.location?.value;
 const actual={...(hasResponse&&typeof payload?.statusCode==='number'?{statusCode:payload.statusCode}:{}),...(hasRequest&&typeof payload?.uri==='string'?{uri:payload.uri}:{}),...(typeof rawLocation==='string'?{location:rawLocation}:{})};
 const expectedKind=Object.hasOwn(expected,'statusCode')?'response':'request';
 const functionErrorPresent=Boolean(testResult?.TestResult?.FunctionErrorMessage)||Boolean(testResult?.error);const functionError=functionErrorPresent||!shapeValid||(hasResponse?'response':hasRequest?'request':'')!==expectedKind;
 const passed=!functionError&&Object.entries(expected).every(([key,value])=>actual[key]===value);
 const compute=Number(testResult?.TestResult?.ComputeUtilization);
 return {caseIndex:index,input:{method:testCase.method??'GET',uri:testCase.uri,host:'uaroute.com',queryKeys:Object.keys(testCase.querystring??{}).sort(),headerKeys:Object.keys(testCase.headers??{}).sort()},expected,actual,outputKind:hasResponse?'response':hasRequest?'request':'invalid',envelopeKeys,parseError,functionErrorPresent,error:functionError?'runtime-error':null,computeUtilization:Number.isFinite(compute)?compute:null,passed};
}
export function assertEdgeRuntimeResults(results){const failed=results.filter(x=>!x.passed).map(x=>x.caseIndex);if(failed.length)throw Error(`edge runtime acceptance failed: cases ${failed.join(',')}`);return true;}
export function validatePrefix(prefix){if(!/^releases\/[0-9]+-[0-9]+$/.test(prefix))throw Error('invalid recovery prefix');return prefix;}
async function cli(args){await execute('aws',args,{maxBuffer:20*1024*1024});}
async function identity(){if((await aws(['sts','get-caller-identity'])).Account!==target.account)throw Error('AWS account mismatch');}
async function assertConfig(bundle){const m=JSON.parse(await readFile(path.join(bundle,'recovery-manifest.json'),'utf8'));const saved=JSON.parse(await readFile(path.join(bundle,m.config.path),'utf8'));const now=await aws(['cloudfront','get-distribution-config','--id',target.distribution]);if(json(saved)!==json(now))throw Error('production distribution drift');return m;}
async function exclusiveAssociations(){const d=await aws(['cloudfront','list-distributions']);const matches=(d.DistributionList?.Items??[]).filter(x=>[x.DefaultCacheBehavior,...(x.CacheBehaviors?.Items??[])].some(b=>(b.FunctionAssociations?.Items??[]).some(a=>a.FunctionARN.endsWith(`/${functionName}`))));if(matches.length!==1||matches[0].Id!==target.distribution)throw Error('unexpected shared edge function association');}
export async function putFile(bucket,key,file,metadata){const input={Bucket:bucket,Key:key,...metadata};const filename=path.join(await mkdtemp(path.join(os.tmpdir(),'uaroute-put-')),'input.json');await writeFile(filename,json(input));await aws(['s3api','put-object','--cli-input-json',`file://${filename}`,'--body',file]);}
async function edgePublish(code,config){await exclusiveAssociations();const live=await aws(['cloudfront','describe-function','--name',functionName,'--stage','LIVE']);const current=path.join(await mkdtemp(path.join(os.tmpdir(),'uaroute-edge-')),'live.js');await aws(['cloudfront','get-function','--name',functionName,'--stage','LIVE',current]);if(digest(await readFile(current))===digest(await readFile(code))&&json(live.FunctionSummary.FunctionConfig)===json(config))return {changed:false};const dev=await aws(['cloudfront','describe-function','--name',functionName,'--stage','DEVELOPMENT']);const configFile=path.join(path.dirname(current),'config.json');await writeFile(configFile,json(config));const updated=await aws(['cloudfront','update-function','--name',functionName,'--if-match',dev.ETag,'--function-config',`file://${configFile}`,'--function-code',`fileb://${path.resolve(code)}`]);
 const results=[];
 for(let i=0;i<baseEdgeRuntimeCases.length;i++){const c=baseEdgeRuntimeCases[i];const file=path.join(path.dirname(current),`test-${i}.json`);await writeFile(file,json(edgeEvent(c)));const test=await aws(['cloudfront','test-function','--name',functionName,'--if-match',updated.ETag,'--stage','DEVELOPMENT','--event-object',`fileb://${file}`]);results.push(inspectEdgeRuntimeCase(c,test,i));}
 assertEdgeRuntimeResults(results);
 await aws(['cloudfront','publish-function','--name',functionName,'--if-match',updated.ETag]);return {changed:true};}
export function objectMetadata(meta){return Object.fromEntries(['ContentType','CacheControl','ContentEncoding','ContentDisposition','ContentLanguage','Expires','Metadata','WebsiteRedirectLocation'].filter(k=>meta[k]!==undefined).map(k=>[k,meta[k]]));}
async function finish(evidence){await cli(['cloudfront','wait','distribution-deployed','--id',target.distribution]);const result=await aws(['cloudfront','create-invalidation','--distribution-id',target.distribution,'--paths','/*']);await writeFile(path.join(evidence,'invalidation-created.json'),json(result));await cli(['cloudfront','wait','invalidation-completed','--distribution-id',target.distribution,'--id',result.Invalidation.Id]);await writeFile(path.join(evidence,'invalidation-completed.json'),json(await aws(['cloudfront','get-invalidation','--distribution-id',target.distribution,'--id',result.Invalidation.Id])));}
export async function verifyPublished(files,bucket=target.bucket){for(const f of files){const meta=await aws(['s3api','head-object','--bucket',bucket,'--key',f.key]);if(meta.ContentLength!==f.size)throw Error(`published size mismatch ${f.key}`);const tmp=path.join(await mkdtemp(path.join(os.tmpdir(),'uaroute-verify-')),'object');await aws(['s3api','get-object','--bucket',bucket,'--key',f.key,tmp]);if(digest(await readFile(tmp))!==f.sha256)throw Error(`published hash mismatch ${f.key}`);if(f.metadata)for(const [k,v] of Object.entries(objectMetadata(f.metadata)))if(json(meta[k])!==json(v))throw Error(`published metadata mismatch ${f.key} ${k}`);}}
async function backup({prefix,evidence}){validatePrefix(prefix);const version=await aws(['s3api','get-bucket-versioning','--bucket',recoveryBucket]);const block=await aws(['s3api','get-public-access-block','--bucket',recoveryBucket]);if(version.Status!=='Enabled'||Object.values(block.PublicAccessBlockConfiguration).some(x=>x!==true))throw Error('private versioned recovery bucket required');const captured=path.join(evidence,'captured');const manifest=await capture({to:captured,...target});await cli(['s3','cp',captured,`s3://${recoveryBucket}/${prefix}/`,'--recursive','--no-progress','--sse','AES256']);const retrieved=path.join(evidence,'retrieved');await cli(['s3','cp',`s3://${recoveryBucket}/${prefix}/`,retrieved,'--recursive','--no-progress']);await recoveryVerify({bundle:retrieved,expectedHash:manifest.bundleSha256,...target});await writeFile(path.join(evidence,'recovery-receipt.json'),json({prefix,bundleSha256:manifest.bundleSha256,bucket:recoveryBucket,objects:manifest.objects.length,retrievedAt:new Date().toISOString(),retrievalVerified:true}));return {bundle:retrieved,manifest};}
export async function deploy(o){await mkdir(o.evidence,{recursive:true});const run=JSON.parse(await readFile(o.run,'utf8'));await releaseVerify({...o,run});await identity();const recovery=await backup(o);await assertConfig(recovery.bundle);await exclusiveAssociations();const saved=JSON.parse(await readFile(path.join(recovery.bundle,recovery.manifest.functions.find(f=>f.arn.endsWith(`/${functionName}`)).description.path),'utf8'));const manifest=JSON.parse(await readFile(path.join(o.bundle,'manifest.json'),'utf8'));const files=[...manifest.files].sort((a,b)=>Number(b.path.startsWith('_next/static/'))-Number(a.path.startsWith('_next/static/')));for(const f of files){const type=f.path.endsWith('.html')?'text/html; charset=utf-8':f.path.endsWith('.txt')?'text/plain; charset=utf-8':f.path.endsWith('.json')?'application/json':f.path.endsWith('.xml')?'application/xml':undefined;const args=['s3','cp',path.join(o.bundle,'out',f.path),`s3://${target.bucket}/${f.path}`,'--no-progress','--cache-control',f.path.startsWith('_next/static/')?'public, max-age=31536000, immutable':'public, max-age=0, must-revalidate'];if(type)args.push('--content-type',type);await cli(args);}
 await edgePublish(path.join(o.bundle,'edge.js'),saved.FunctionSummary.FunctionConfig);await finish(o.evidence);await verifyPublished(files.map(f=>({...f,key:f.path})));const contract=await fetch('https://uaroute.com/referral-contract.json');if(!contract.ok||!(contract.headers.get('content-type')??'').includes('application/json')||digest(Buffer.from(await contract.arrayBuffer()))!==digest(await readFile(path.join(o.bundle,'out','referral-contract.json'))))throw Error('live receiver contract mismatch');await cp(path.join(o.bundle,'out'),'out',{recursive:true});await execute('node',['scripts/seo-http.mjs','https://uaroute.com','--output',path.join(o.evidence,'live-http.json')],{maxBuffer:20*1024*1024});await writeFile(path.join(o.evidence,'success.json'),json({sourceSha:o.sha,runId:o.runId,releaseSha256:o.expectedHash,edgeSha256:o.expectedEdgeHash,recoveryPrefix:o.prefix,recoveryHash:recovery.manifest.bundleSha256,publishedObjects:files.length,verifiedAt:new Date().toISOString()}));}
export async function edgeCheck(o){
 await mkdir(o.evidence,{recursive:true});
 const resultPath=path.join(o.evidence,'edge-runtime-tests.json');let report={schemaVersion:1,caseResults:[],functionCodeMatch:false,completed:false};
 const save=()=>writeFile(resultPath,json(report));
 try{
  const run=JSON.parse(await readFile(o.run,'utf8'));const verified=await releaseVerify({...o,run});report.candidate={runId:verified.runId,sourceSha:verified.sourceSha,releaseSha256:verified.releaseSha256,edgeSha256:verified.edgeSha256};
  await identity();report.awsAccountValidated=true;await exclusiveAssociations();report.exclusiveAssociationValidated=true;
  const candidate=await readFile(path.join(o.bundle,'edge.js'));
  const description=await aws(['cloudfront','describe-function','--name',functionName,'--stage','DEVELOPMENT']);
  const dir=await mkdtemp(path.join(os.tmpdir(),'uaroute-edge-check-'));const devPath=path.join(dir,'development.js');
  await aws(['cloudfront','get-function','--name',functionName,'--stage','DEVELOPMENT',devPath]);
  const candidateHash=digest(candidate),developmentHash=digest(await readFile(devPath));
  report.functionCodeMatch=candidateHash===developmentHash;report.candidateEdgeSha256=candidateHash;report.developmentEdgeSha256=developmentHash;
  if(!report.functionCodeMatch){report.error='development-function-code-mismatch';await save();throw Error('development function code does not match verified candidate');}
  for(let i=0;i<edgeRuntimeCases.length;i++){
   const c=edgeRuntimeCases[i],file=path.join(dir,`test-${i}.json`);await writeFile(file,json(edgeEvent(c)));
   try{const test=await aws(['cloudfront','test-function','--name',functionName,'--if-match',description.ETag,'--stage','DEVELOPMENT','--event-object',`fileb://${file}`]);report.caseResults.push(inspectEdgeRuntimeCase(c,test,i));}
   catch{report.caseResults.push({caseIndex:i,input:{method:c.method??'GET',uri:c.uri,host:'uaroute.com',queryKeys:Object.keys(c.querystring??{}).sort(),headerKeys:Object.keys(c.headers??{}).sort()},expected:expectedFor(c),actual:{},outputKind:'invalid',envelopeKeys:[],parseError:false,functionErrorPresent:true,error:'test-invocation-failed',computeUtilization:null,passed:false});}
  }
  report.completed=true;await save();assertEdgeRuntimeResults(report.caseResults);
 }catch(error){if(!report.error)report.error=error.message==='edge runtime acceptance failed'||error.message.startsWith('edge runtime acceptance failed:')?'case-acceptance-failed':'read-only-edge-check-failed';await save();throw error;}
}
export async function verifyRestoredLive(m){const results=[];for(const [key,url,type] of [['index.html','/','text/html'],['sitemap.xml','/sitemap.xml','application/xml'],['referral-contract.json','/referral-contract.json','application/json']]){const expected=m.objects.find(x=>x.key===key);if(!expected)throw Error(`missing critical recovery object ${key}`);const response=await fetch(`https://uaroute.com${url}`,{redirect:'manual',signal:AbortSignal.timeout(30000)});const hash=digest(Buffer.from(await response.arrayBuffer()));if(response.status!==200||!(response.headers.get('content-type')??'').includes(type)||hash!==expected.sha256)throw Error(`restored live mismatch ${url}`);results.push({url,status:response.status,sha256:hash});}for(const [url,status,location] of [['/contacts?utm_source=uaroute',308,'https://uaroute.com/about/?utm_source=uaroute'],['/provider/unknown',404,undefined]]){const response=await fetch(`https://uaroute.com${url}`,{redirect:'manual',signal:AbortSignal.timeout(30000)});if(response.status!==status||location&&response.headers.get('location')!==location)throw Error(`restored edge mismatch ${url}`);results.push({url,status});}return {results,verifiedAt:new Date().toISOString()};}
export async function rollback(o){validatePrefix(o.prefix);await identity();await mkdir(o.evidence,{recursive:true});const current=await backup({prefix:o.currentPrefix,evidence:path.join(o.evidence,'before-rollback')});await cp(path.join(o.evidence,'before-rollback','recovery-receipt.json'),path.join(o.evidence,'recovery-receipt.json'));const bundle=path.join(o.evidence,'retrieved');await cli(['s3','cp',`s3://${recoveryBucket}/${o.prefix}/`,bundle,'--recursive','--no-progress']);const m=await recoveryVerify({bundle,expectedHash:o.expectedHash,...target});await exclusiveAssociations();const captured=JSON.parse(await readFile(path.join(bundle,m.config.path),'utf8'));const now=await aws(['cloudfront','get-distribution-config','--id',target.distribution]);if(json(now.DistributionConfig)!==json(captured.DistributionConfig))throw Error('rollback distribution config changed; reviewed manual recovery required');await assertConfig(current.bundle);for(const obj of [...m.objects].sort((a,b)=>Number(b.key.startsWith('_next/static/'))-Number(a.key.startsWith('_next/static/'))))await putFile(target.bucket,obj.key,path.join(bundle,obj.path),objectMetadata(obj.metadata));for(const f of m.functions){if(!f.arn.endsWith(`/${functionName}`))throw Error('unexpected rollback function');const desc=JSON.parse(await readFile(path.join(bundle,f.description.path),'utf8'));await edgePublish(path.join(bundle,f.code.path),desc.FunctionSummary.FunctionConfig);}await finish(o.evidence);await verifyPublished(m.objects);await writeFile(path.join(o.evidence,'live-http.json'),json(await verifyRestoredLive(m)));await writeFile(path.join(o.evidence,'success.json'),json({mode:'rollback',currentRecoveryPrefix:o.currentPrefix,currentRecoveryHash:current.manifest.bundleSha256,prefix:o.prefix,bundleSha256:m.bundleSha256,verifiedObjects:m.objects.length,verifiedAt:new Date().toISOString()}));}
async function main(){const [mode,...args]=process.argv.slice(2);const o={};for(let i=0;i<args.length;i+=2){if(!args[i].startsWith('--')||!args[i+1])throw Error('expected --key value');o[args[i].slice(2)]=args[i+1];}if(mode==='deploy')await deploy(o);else if(mode==='rollback')await rollback(o);else if(mode==='edge-check')await edgeCheck(o);else throw Error('use deploy, rollback, or edge-check');}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))main().catch(e=>{console.error(e.message);process.exitCode=1;});
